services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:1.29
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:81
    networks:
      - web_network

  database:
    container_name: database
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017
    volumes:
      - ./configs/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - .dev_data:/data/db:rw
    networks:
      - database_network

  api:
    container_name: api
    image: node:23.8.0
    environment:
      - EXPRESS_PORT=2000
      - NODE_ENV=dev
      - MONGO_USER=catalogDatabaseApi
      - MONGO_PASSWORD=qwe123
      - MONGO_DATABASE=catalogDB
      - NODE_ENV=development
    networks:
      - web_network
      - database_network
    volumes:
      - ./api:/api:rw
      - ./logs:/logs:rw
      - ./keys:/keys:rw
    working_dir: /api
    command: bash -c "npm install && npm run dev"
    depends_on:
      - reverse_proxy
      - database
      - whitelist

  test:
    container_name: test
    image: node:23.8.0
    environment:
      - EXPRESS_PORT=2000
      - MONGO_USER=catalogDatabaseApi
      - MONGO_PASSWORD=qwe123
      - MONGO_DATABASE=catalogDB
      - TEST_USER=testUser
      - TEST_PASSWORD=password124
      - NODE_OPTIONS=$NODE_OPTIONS --experimental-vm-modules
      - NODE_ENV=test
    volumes:
      - ./api:/api:rw
      - ./logs:/logs:rw
      - ./keys/:/keys:rw
      - ./configs/jest.config.js:/jest.config.js:ro
    working_dir: /api
    command: bash -c "npm install && npm test"
    depends_on:
      - database
      - whitelist
    networks:
      - database_network

  whitelist:
    container_name: whitelist
    image: redis:8.0
    networks:
      - database_network

networks:
  web_network:
    name: web_network
  database_network:
    name: database_network

volumes:
  dev_data:
